/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.soen6461.scrapping.ui;

import com.soen6461.analysis.AnalysisFacade;
import com.soen6461.scrapping.scrapper.ScrapingFacade;
import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JDesktopPane;
import javax.swing.JFileChooser;

/**
 *
 * @author khurram
 */
public class CSVForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form CSVForm
     */
    public CSVForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        btn_select_file = new javax.swing.JButton();
        lblFilePath = new javax.swing.JLabel();
        btnStartScrapping = new javax.swing.JButton();
        jButtonViewXML = new javax.swing.JButton();
        jButtonViewCSV = new javax.swing.JButton();
        jButtonSaveXML = new javax.swing.JButton();
        jButtonStartAnalysis = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Select a CSV File");

        btn_select_file.setText("Select CSV ");
        btn_select_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_select_fileActionPerformed(evt);
            }
        });

        lblFilePath.setText(" ");

        btnStartScrapping.setText("Start Scrapping");
        btnStartScrapping.setEnabled(false);
        btnStartScrapping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartScrappingActionPerformed(evt);
            }
        });

        jButtonViewXML.setText("View XML");
        jButtonViewXML.setEnabled(false);
        jButtonViewXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewXMLActionPerformed(evt);
            }
        });

        jButtonViewCSV.setText("View CSV");
        jButtonViewCSV.setEnabled(false);

        jButtonSaveXML.setText("Save XML");
        jButtonSaveXML.setEnabled(false);
        jButtonSaveXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveXMLActionPerformed(evt);
            }
        });

        jButtonStartAnalysis.setText("Start Analysis");
        jButtonStartAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartAnalysisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_select_file)
                            .addComponent(btnStartScrapping)
                            .addComponent(jButtonSaveXML))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonStartAnalysis)
                            .addComponent(jButtonViewXML)
                            .addComponent(jButtonViewCSV))))
                .addContainerGap(444, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addComponent(lblFilePath)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_select_file)
                    .addComponent(jButtonViewCSV))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonViewXML)
                    .addComponent(btnStartScrapping))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSaveXML)
                    .addComponent(jButtonStartAnalysis))
                .addContainerGap(285, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_select_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_select_fileActionPerformed
        // TODO add your handling code here:
        
        JFileChooser c = new JFileChooser();
        c.showOpenDialog(null);
        File f = c.getSelectedFile();
        String filename = f.getAbsolutePath();
        lblFilePath.setText(filename);
        btnStartScrapping.setEnabled(true);
    }//GEN-LAST:event_btn_select_fileActionPerformed

    private void btnStartScrappingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartScrappingActionPerformed
        // TODO add your handling code here:
        ScrapingFacade sc  = ScrapingFacade.getInstance();
        sc.scrape(lblFilePath.getText());
        
        jButtonSaveXML.setEnabled(true);
        //
        
    }//GEN-LAST:event_btnStartScrappingActionPerformed

    private void jButtonViewXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewXMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonViewXMLActionPerformed

    private void jButtonSaveXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveXMLActionPerformed
        // TODO add your handling code here:
        JFileChooser c = new JFileChooser();
        c.showOpenDialog(null);
        File f = c.getSelectedFile();
        String filename = f.getAbsolutePath();
        ScrapingFacade sc  = ScrapingFacade.getInstance();
        lblFilePath.setText(filename);
        sc.saveFile(filename);
    }//GEN-LAST:event_jButtonSaveXMLActionPerformed

    private void jButtonStartAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartAnalysisActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
       AnalysisFacade facade= AnalysisFacade.getInstance();
       facade.analyseData(lblFilePath.getText());
       
       
         BarChart bc = new BarChart();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(bc); 
       
        //desktopPane.add()
        bc.setVisible(true);
    }//GEN-LAST:event_jButtonStartAnalysisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartScrapping;
    private javax.swing.JButton btn_select_file;
    private javax.swing.JButton jButtonSaveXML;
    private javax.swing.JButton jButtonStartAnalysis;
    private javax.swing.JButton jButtonViewCSV;
    private javax.swing.JButton jButtonViewXML;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFilePath;
    // End of variables declaration//GEN-END:variables
}
